= FLaP &mdash; Flat LaTeX Projects
:Author:    Franck Chauvel
:Email:     franck.chauvel@gmail.com

link:https://pypi.python.org/pypi/FLaP[image:https://img.shields.io/pypi/v/FLaP.svg[]]
link:http://www.gnu.org/licenses/gpl-3.0[image:https://img.shields.io/pypi/l/FLaP.svg[]]
link:https://codeship.com/projects/97486[image:https://img.shields.io/codeship/ad32e1e0-27d8-0133-8e78-7af7072ae828.svg[]]
link:https://codecov.io/gh/fchauvel/flap[image:https://img.shields.io/codecov/c/github/fchauvel/flap/master.svg[]]
link:https://www.codacy.com/app/fchauvel/flap/dashboard[image:https://img.shields.io/codacy/grade/df4826670c71444ca487434d612e96d7.svg[]]
link:http://pypi-ranking.info/module/FLaP[image:https://img.shields.io/pypi/dm/FLaP.svg[]]

Flap is a simple utility that flattens LaTeX projects. It takes a
well-organised LaTeX project&mdash;one you so carefully crafted&mdash;and
merged it into a vulgar single LaTeX file in a 'flat' directory.

*Why?* Some publishers require one such flat structure when you submit
the sources of your manuscript, and I got tired to flatten the sources
by hand.

*Another one?* There already a couple of tools that merge latex projects
such as http://www.ctan.org/pkg/latexpand[latexpand], http://www.ctan.org/pkg/flatex[flatex]
or http://www.ctan.org/pkg/flatten[flatten]. As far as I know, they only merge
TeX files, without moving graphics around. I learned recently about
http://www.ctan.org/pkg/texdirflatten[texdirflatten], which seems to be
an alternative, but I haven't tried it.

== Installation
FLaP *requires* Python 3 (3.2, 3.3, 3.4 and 3.5 are tested). The easiest way
to install FLaP is to use pip using `pip install flap`.

Alternatively, you may download the sources distribution and use `python
setup.py install`

== Usage Example

Prior to v0.4.1 (included), we invoke FLaP using:
----
$> python -m flap project/main.tex output/directory
----

For the newest development version, use:
----
$> flap project/main.tex output/directory
----

See also the link:https://pythonhosted.org/FLaP/[online FLaP documentation].

== Contact Us

If you give FLaP a try, please report any bugs, issues or feature request using the
link:https://github.com/fchauvel/flap/issues[issue tracker].

Feel free to share any question or comment on our mailto:flap-general@freelists.org[FLaP mailing list]. Note that you must
subscribe first by sending an email to 'flap-general-request@freelists.org' with 'subscribe' in the Subject field OR by
visiting link:http://www.freelists.org/list/flap-general[our subscription page].


