= FLaP &mdash; Flat LaTeX Projects
:Author:    Franck Chauvel
:Email:     franck.chauvel@gmail.com

image:https://img.shields.io/pypi/v/FLaP.svg[]
image:https://img.shields.io/pypi/l/FLaP.svg[]
link:https://codeship.com/projects/97486[image:https://img.shields.io/codeship/ad32e1e0-27d8-0133-8e78-7af7072ae828.svg[]]
link:https://codecov.io/gh/fchauvel/flap[image:https://img.shields.io/codecov/c/github/fchauvel/flap/master.svg[]]
image:https://img.shields.io/pypi/dm/FLaP.svg[]

Flap is a simple utility that flattens LaTeX projects. It takes a well organised LaTeX project 
&mdash; one you so carefully crafted &mdash; and merged it into a vulgar single LaTeX file 
in a flat directory.

*Why?* Some publishers require such a flat structure when you submit the sources of your 
manuscripts, and I got tired to flatten the sources by hand.

*Another one?* There already a couple of tools that merge latex project such as http://www.ctan.org/pkg/latexpand[latexpand],
http://www.ctan.org/pkg/flatex[flatex] or http://www.ctan.org/pkg/flatten[flatten]. As far as I know, they only merge
TeX files, without moving graphics around. I learned recently about
http://www.ctan.org/pkg/texdirflatten[texdirflatten], which seems to be an alternative, but I haven't tried it.

== Installation
FLaP *requires* Python 3 (3.2, 3.3 and 3.4 are tested). The easiest way to install FLaP is to use pip using `pip install flap`.

Alternatively, you may download the sources distribution and use `python setup.py install`

== Usage Example

Use FLaP in the command line:

----
$> python3 -m flap project/main.tex output/directory
----

See also the link:https://pythonhosted.org/FLaP/[online documentation].

== Contact

If you get the change to give it a try, please report any bugs, issues or feature request using 
the link:https://github.com/fchauvel/flap/issues[issue tracker].
Should you need any further information, feel free to email mailto:franck.chauvel@gmail.com[me]


=== TODO

Here is a list of features, which are not yet supported:

. Refactoring, break down engine.py into one file per directive
. Support for backward relative links in directives, for instance `\input{../img/foo}`.
. Support for star-form of directives, such as `\includegraphics*{foo}`

== Included in Next Release

Nothing yet.

