= FLaP &mdash; Flat LaTeX Projects
:Author:    Franck Chauvel
:Email:     franck.chauvel@gmail.com

Flap is a simple utility that flattens LaTeX projects. It takes a well organised LaTeX project 
&mdash; one you so carefully crafted &mdash; and merged it into a vulgar single LaTeX file 
in a flat directory.

*Why?* Some publishers require such a flat structure when you submit the sources of your 
manuscripts, and I got tired to flatten the sources by hand.

== TODOs

Here is a list of features, which are not yet supported:

 * Support for backward relative links in directives, for instance `\input{../img/foo}`.
 * Do not merge directives when the line is commented out
 * Provide some feedback to the user
 * Test on a UNIX-like file system

== Contact

If you get the change to give it a try, please report any bugs, issues or feature request using 
the link:https://github.com/fchauvel/flap/issues[issue tracker].
Should you need any further information, feel free to email mailto:franck.chauvel@gmail.com[me]

